# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.

ENV["SEARCHENGINE_ENV"] = 'test'
require 'simplecov'
SimpleCov.start

require 'rspec'

file_pattern = File.join("./", "*.rb")
files_to_include = Dir.glob(file_pattern)
files_to_include.each do |file| 
  require file
end

# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  #config.filter_run :focus
end
